import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Data-fetch-mastering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full hydrated`}
    >
      <body className="min-h-full flex flex-col suppressHydrationWarning">
        {/* <main> */}
          <Navbar></Navbar>
          {children}
        {/* </main> */}
      </body>
    </html>
  );
}
